col CONSTRAINT_NAME format a20
col CONSTRAINT_TYPEi format a10
col STATUS format a20
col VALIDATED format a20

SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, STATUS, VALIDATED FROM USER_CONSTRAINTs WHERE TABLE_NAME='EMPLOYEES' AND
CONSTRAINT_NAME='CHECK_COMP';

ALTER TABLE employees ADD CONSTRAINT check_comp 
   CHECK (salary + (commission_pct*salary) <= 5000)
   DISABLE;

SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, STATUS, VALIDATED FROM USER_CONSTRAINTs WHERE TABLE_NAME='EMPLOYEES' AND
CONSTRAINT_NAME='CHECK_COMP';

