col CONSTRAINT_NAME format a20
col CONSTRAINT_TYPEi format a10
col STATUS format a20
col VALIDATED format a20

SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, STATUS, VALIDATED FROM USER_CONSTRAINTs WHERE TABLE_NAME='EMPLOYEES';

ALTER TABLE employees
   ENABLE NOVALIDATE PRIMARY KEY
   ENABLE NOVALIDATE CONSTRAINT emp_last_name_nn;

SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, STATUS, VALIDATED FROM USER_CONSTRAINTs WHERE TABLE_NAME='EMPLOYEES';

ALTER TABLE employees
   ENABLE VALIDATE PRIMARY KEY
   ENABLE VALIDATE CONSTRAINT emp_last_name_nn;

SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, STATUS, VALIDATED FROM USER_CONSTRAINTs WHERE TABLE_NAME='EMPLOYEES';

